name = "hiroshima-mirai-project"
pages_build_output_dir = "."
compatibility_date = "2026-09-07"

[[d1_databases]]
binding = "DB"
database_name = "hiroshima-mirai"
database_id = "a935b517-c8bb-4c6c-ad50-dbf3acdbfd45"
